name: Release Drafter

on:
  push:
    branches:
      - main

  pull_request:
    types: [opened, reopened, synchronize]

  pull_request_target:
    types: [opened, reopened, synchronize]

permissions: {}

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a GitHub release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: release-drafter/release-drafter@v6
        with:
         config-name: release-drafter-config.yml
         disable-autolabeler: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
